const API_URL = process.env.REACT_APP_API_URL;
const API_KEY = process.env.REACT_APP_API_KEY;
const WEB_SOCKET = process.env.REACT_APP_WEB_SOCKET;
const TASK_TYPE1_TEXT="TODO";
const TASK_TYPE2_TEXT="INPROGRESS";
const TASK_TYPE3_TEXT="DONE";
const TASK_TYPE1="1";
const TASK_TYPE2="2";
const TASK_TYPE3="3";
const TOTAL_COLUMNS=3;
export { API_URL, 
    API_KEY,
    WEB_SOCKET,
    TASK_TYPE1,
    TASK_TYPE2,
    TASK_TYPE3,
    TOTAL_COLUMNS,
    TASK_TYPE1_TEXT,
    TASK_TYPE2_TEXT,
    TASK_TYPE3_TEXT };
