let API_URL = process.env.REACT_APP_API_URL;
let API_KEY = process.env.REACT_APP_API_KEY;
let WEB_SOCKET = process.env.REACT_APP_WEB_SOCKET;
let TASK_TYPE1="1";
let TASK_TYPE2="2";
let TASK_TYPE3="3";
let TOTAL_COLUMNS=3;
export { API_URL, API_KEY,WEB_SOCKET,TASK_TYPE1,TASK_TYPE2,TASK_TYPE3,TOTAL_COLUMNS };
